CREATE SCHEMA IF NOT EXISTS todo;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS todo.TB_USER
(
    id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    name varchar(200),
    email varchar(255) unique NOT NULL,
    password varchar(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS todo.TB_ROLE
(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name varchar(255) NOT null,
    CONSTRAINT tb_role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS todo.TB_USER_ROLE (
	user_id uuid NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT tb_user_role_pkey PRIMARY KEY (user_id, role_id)
);

-- users.tb_user_role foreign keys
ALTER TABLE todo.TB_USER_ROLE ADD FOREIGN KEY (user_id) REFERENCES todo.TB_USER(id);
ALTER TABLE todo.TB_USER_ROLE ADD FOREIGN KEY (role_id) REFERENCES todo.TB_ROLE(id);


INSERT INTO todo.TB_ROLE (role_name) VALUES
	 ('ROLE_OPERATOR'),
	 ('ROLE_ADMIN');

INSERT INTO todo.TB_USER (id, email,"name","password") VALUES
	 ('1728d3f6-9282-4021-b186-4d458bdbc038', 'admin@todo.com','Administrador TODO','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu'),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6', 'sub_admin@todo.com','Sub TODO','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu'),
	 ('73d26316-2ecf-4bec-9cb9-c334be24ccbf', 'test@todo.com','Common TODO','$2a$10$NYFZ/8WaQ3Qb6FCs.00jce4nxX9w7AkgWVsQCG6oUwTAcZqP9Flqu');

INSERT INTO todo.TB_USER_ROLE (user_id,role_id) VALUES
	 ('1728d3f6-9282-4021-b186-4d458bdbc038',1),
	 ('1728d3f6-9282-4021-b186-4d458bdbc038',2),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6',1),
	 ('2af448b1-a8b4-403e-8405-2c085f8fe0b6',2),
	 ('73d26316-2ecf-4bec-9cb9-c334be24ccbf',1);

CREATE TABLE todo.tb_todo (
	id uuid NOT NULL,
	created_date timestamp NOT NULL,
	last_updated_date timestamp NOT NULL,
	title varchar(255) NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT tb_todo_pkey PRIMARY KEY (id)
);

CREATE TABLE todo.tb_task (
	id uuid NOT NULL,
	conclusion timestamp NULL,
	created_date timestamp NOT NULL,
	last_updated_date timestamp NOT NULL,
	"name" varchar(255) NOT NULL,
	status bool NOT NULL,
	todo_id uuid NOT NULL,
	CONSTRAINT tb_task_pkey PRIMARY KEY (id)
);

ALTER TABLE todo.tb_task ADD FOREIGN KEY (todo_id) REFERENCES todo.tb_todo(id);