version: "3.5"

services:

  dbpostgres_sellers:
    image: postgres:12.0-alpine
    container_name: dbpostgres_sellers
    volumes:
      - ./postgres/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
    environment:
      POSTGRES_DB: marina_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    expose:
      - '5432'
    ports:
      - 5432:5432
    restart: unless-stopped
   
  register_sellers:
    container_name: register_sellers
    depends_on:
      - dbpostgres_sellers
    build:
      context: ./register
      dockerfile: Dockerfile
    image: my-register_sellers:latest
    restart: always
    expose:
      - '8761'
    ports:
      - 8761:8761
      
  oauth_sellers:
    container_name: oauth_spring_boot
    depends_on:
      - register_sellers
      - dbpostgres_sellers
    build:
      context: ./oauth
      dockerfile: Dockerfile
    image: my-oauth_sellers:latest
    restart: always
    expose:
      - '5051'
    ports:
      - 5051:5051
    environment: 
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://register_sellers:8761/eureka
      
  gateway_sellers:
    container_name: gateway_sellers
    depends_on:
      - register_sellers
      - dbpostgres_sellers
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: my-gateway_sellers:latest
    restart: always
    expose:
      - '8765'
    ports:
      - 8765:8765
    environment: 
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://register_sellers:8761/eureka
      
#  core_sellers:
#    container_name: core_sellers
#    depends_on:
#      - dbpostgres_sellers
#      - register_sellers
#    build:
#      context: ./core
#      dockerfile: Dockerfile
#    image: my-core_sellers:latest
#    restart: always
#    ports:
#      - 5055:5055
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgres_sellers:5432/marina_test?createDatabaseIfNotExist=true&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=postgres
#     - SPRING_DATASOURCE_PASSWORD=toor
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - eureka.client.serviceUrl.defaultZone=http://register_sellers:8761/eureka

