server:
#  port: 5315
#  error:
#    include-stacktrace: NEVER
#  port: ${PORT:5055}
spring:
  application:
    name: notification
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

eureka:
  instance: instance-id=${spring:application:name}:${spring:application:instance_id:${random:value}}
  client:
    service-url:
      defaultzone: http://localhost:8761

rabbitmq:
  payment:
    queue: pos.payment.queue
    exchange: pos.payment.exchange
    routing: pos.payment.routing

link:
  host:
    email: http://localhost:8761/valid-email/